# Generated by Django 4.0.1 on 2022-01-25 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_review_ticket_remove_review_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='ticket_associe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.ticket'),
        ),
        migrations.AlterField(
            model_name='review',
            name='user_associe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.user'),
        ),
    ]
